# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_auto_20171120_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='Quotation',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='quote',
            new_name='quotation',
        ),
    ]
