# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_birthdate'),
        ('quotation', '0006_auto_20171120_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favorites',
        ),
        migrations.AddField(
            model_name='quotation',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorites', to='login.User'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
