# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_favorite_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='quotation',
            field=models.CharField(max_length=255),
        ),
    ]
